name: Tag on PR merge

on:
  workflow_dispatch:
  pull_request:
#     types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    if:  startsWith(github.head_ref, 'release/')

    steps:
      - run: echo "The head of this PR starts with 'release/'"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: Get version
        id: get-version
        run: |
          if [[ "${{ github.head_ref }}" =~ ^release\/(.*)$ ]]; then
            version="${BASH_REMATCH[1]}"
            echo "Version detected: ${version}"
            echo "::set-output name=version::${version}"
          else
            echo "Does not match release branch format"
            exit 1
          fi
          
      - name: Tag release
        uses: actions/github-script@v4
        with:
          script: |
            console.log("Attempting to delete existing ref")
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "refs/tags/${{steps.get-version.outputs.version}}"
                })
            } catch (e) {
              console.log("The release tag doesn't exist yet", e)
            }
            console.log("Attempting to create new ref")
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.get-version.outputs.version}}",
              sha: "${{github.event.pull_request.head.sha}}"
            })
