name: Tag on PR merge

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    if:  startsWith(github.head_ref, 'release/')

    steps:
      - run: echo "The head of this PR starts with 'release/'"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Log
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.head_ref }}
          
      - name: Get version
        id: get-version
        run: |
          if [[ "${{ github.head_ref }}" =~ ^release\/.*\/(v.*)$ ]]; then
            version="${BASH_REMATCH[1]}"
            echo "Version detected: ${version}"
            echo "::set-output name=version::${version}"
          else
            echo "Does not match release branch format"
            exit 1
          fi

      - name: Tag release
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{gihub.head_ref}}",
              sha: "${{github.event.pull_request.head.sha}}"
            })
