name: Tag on PR merge

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: Log
        run: |
          git rev-parse --verify HEAD
        
