name: Tag on PR merge

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    if:  startsWith(github.head_ref, 'release/')

    steps:
      - run: echo "The head of this PR starts with 'release/'"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Log
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.event.pull_request }}
        
